###
GET http://localhost:3000/todos/
Content-Type:text/html


###
GET http://localhost:3000/todos/?status=TO%20DO
Content-Type:application/json


###
//GET http://localhost:3000/todos/?status=To%20Garden

###
GET http://localhost:3000/todos/?priority=HIGH;
Content-Type: application/json

###
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS
Content-Type:application/json


###
GET http://localhost:3000/todos/?search_q=Buy
Content-Type: application/json


###
GET http://localhost:3000/todos/?category=WORK&status=DONE
Content-Type: application/json

###
GET http://localhost:3000/todos/?category=HOME
Content-Type:application/json

###
GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH
Content-Type:application/json


###
GET http://localhost:3000/todos/4/
Content-Type:application/json


###
GET http://localhost:3000/todos/agenda/?date=2021-02-22



###
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 6,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}

###
PUT http://localhost:3000/todos/4/

{
    "status":"Done"
}


###
PUT http://localhost:3000/todos/3/

{
    "priority":"HIGH"
}

###
PUT http://localhost:3000/todos/6/

{
    "todo":"Clean the garden"
}

###
PUT http://localhost:3000/todos/3/

{
    "category":"LEARNING"
}


###
PUT http://localhost:3000/todos/8/

{
      "dueDate": "2021-01-12"
}

###
DELETE http://localhost:3000/todos/2/

